### ISSUE TITLE
kann beim kategorieeintrag fuer 'version' erstellen das feld  'patchlevel' nicht setzen

### ISSUE THREAD

**Issue by frisbee23** [bheisig/i-doit-api-client-php#9] opened 2018-07-16 11:55 UTC
### Expected behavior
       $entryID = $category->create(
            $jdkID,
            'C__CATG__VERSION',
            [
                'title' => '1.8.0',
                'description' => 'API TEST5',
                // patchlevel scheint nicht zu funktionieren
            'servicepack' => 'servicepack',
            'kernel' =>'kernel',
            'patchlevel' =>'SOMETEXTHERE'

            ]
        );
  print_r ($category->read($jdkID, 'C__CATG__VERSION', $entryID));

    [0] => Array
        (
            [id] => 104
            [objID] => 73415
            [title] => 1.8.0
            [servicepack] => servicepack
            [kernel] => kernel
            [patchlevel] => SOMETEXTHERE
            [description] => API TEST5
        )

### Actual behavior

 ```
  Array
        (
            [id] => 107
            [objID] => 73415
            [title] => 1.8.0
            [servicepack] => servicepack
            [kernel] => kernel
            [patchlevel] =>
            [description] => API TEST5
        )
```

### Steps to reproduce the behavior

just follow my code up above, it's pretty basic..

### Environment

| Question                  | Answer            |
| ------------------------- | ----------------- |
| bheisig/idoitapi version  | 0.6 via composer            |
| PHP version               | 7.0.30           |
| i-doit version            | 1.10.1 pro    |
| i-doit API add-on version | 1.9            |

### Server logs

Excerpt taken from `/var/log/apache2/error.log`:

~~~
192.168.13.21 - - [16/Jul/2018:13:50:39 +0200] "POST /src/jsonrpc.php HTTP/1.1" 200 642 "-" "bheisig/idoitapi 0.6"
192.168.13.21 - - [16/Jul/2018:13:50:39 +0200] "POST /src/jsonrpc.php HTTP/1.1" 200 301 "-" "bheisig/idoitapi 0.6"
192.168.13.21 - - [16/Jul/2018:13:50:39 +0200] "POST /src/jsonrpc.php HTTP/1.1" 200 110 "-" "bheisig/idoitapi 0.6"
192.168.13.21 - - [16/Jul/2018:13:50:39 +0200] "POST /src/jsonrpc.php HTTP/1.1" 200 434 "-" "bheisig/idoitapi 0.6"

192.168.13.21 - - [16/Jul/2018:13:50:39 +0200] "POST /src/jsonrpc.php HTTP/1.1" 200 80 "-" "bheisig/idoitapi 0.6"


~~~

Excerpt taken from `/var/www/html/i-doit/log/api_*.log`:

~~~
[2018-07-16 13:52:40 0.07794100] INFO: JSON-RPC controller started for request: array (  'version' => '2.0',  'method' => 'cmdb.category.create',  'params' =>   array (    'objID' => 73415,    'data' =>     array (      'title' => '1.8.0',      'description' => 'API TEST5',      'servicepack' => 'servicepack',      'kernel' => 'kernel',      'patchlevel' => 'patchlevel',    ),    'category' => 'C__CATG__VERSION',    'apikey' => '2c6goba23d',  ),  'id' => 5,)
[2018-07-16 13:52:40 0.18825700] INFO: Transmitting response: {"jsonrpc":"2.0","result":[{"id":"109","objID":"73415","title":"1.8.0","servicepack":"servicepack","kernel":"kernel","patchlevel":"","description":"API TEST5"},{"id":"110","objID":"73415","title":"1.8.0","servicepack":"servicepack","kernel":"kernel","patchlevel":"","description":"API TEST5"},{"id":"111","objID":"73415","title":"1.8.0","servicepack":"servicepack","kernel":"kernel","patchlevel":"","description":"API TEST5"},{"id":"112","objID":"73415","title":"1.8.0","servicepack":"servicepack","kernel":"kernel","patchlevel":"","description":"API TEST5"}],"id":6}

~~~

**Comment by bheisig** [comment] 2018-07-31 14:52
Hi @frisbee23,

Thanks for your feedback. Your described behavior looks like something could be broken within i-doit. Ergo it's not related to this project. Please report these types of issues [here](https://help.i-doit.com/) to get it fixed by the i-doit devs. Nonetheless, I cannot reproduce this error with i-doit pro 1.11 and API add-on 1.9.1. Maybe you should update before reporting this issue.

My request:

~~~
{
    "version": "2.0",
    "method": "cmdb.category.create",
    "params": {
        "objID": 513,
        "data": {
            "title": "1.12",
            "servicepack": "Nope",
            "kernel": "Nope",
            "patchlevel": "Nope",
            "description": "This is just a test"
        },
        "category": "C__CATG__VERSION",
        "apikey": "xxx",
        "language": "en"
    },
    "id": 1
}
~~~

Server-side response for `cmdb.category.read`:

~~~
{
    "jsonrpc": "2.0",
    "result": [
        […],
        {
            "id": "136",
            "objID": "513",
            "title": "1.12",
            "servicepack": "Nope",
            "kernel": "Nope",
            "patchlevel": "Nope",
            "description": "This is just a test"
        }
    ],
    "id": 2
}
~~~

Greetings,
Ben

**Closed by bheisig** 2018-07-31 14:52 UTC
